config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ruby-octopus.sh
        container: qc.acc_blurry-lemon-affenpinscher
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-mauve-tzu.sh
        container: qc.doc_sunny-coral-cow
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-jade-stingray.sh
        container: qc.doc_beady-chartreuse-tzu
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-bronze-gharial.sh
        container: qc.doc_crabby-bronze-rabbit
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-charcoal-moose.sh
        container: qc.lic_scanty-lime-cuscus
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chestnut-cuttlefish.sh
        container: qc.sec_stinky-periwinkle-cockroach
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-scarlet-cuscus.sh
        container: qc.sty_greasy-corn-ant
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ready-auburn-sloth.sh
        container: qc.uni_shaky-chartreuse-quokka
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-taupe-urchin.sh
        container: qc.ver_bumpy-mauve-rottweiler
timeout: 5400
