config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-seashell-axolotl.sh
        container: qc.acc_silly-dandelion-cat
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-rose-guppy.sh
        container: qc.doc_goopy-flax-owl
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-jade-mongoose.sh
        container: qc.doc_tasty-harlequin-lionfish
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-apricot-snake.sh
        container: qc.doc_shabby-orchid-millipede
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-eggplant-dragonfly.sh
        container: qc.lic_lumpy-auburn-bongo
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-crimson-akbash.sh
        container: qc.sec_queasy-pumpkin-gharial
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-black-coati.sh
        container: qc.sty_cheeky-red-russel
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-champagne-spider.sh
        container: qc.uni_wheezy-corn-pig
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp-sacs get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cornflower-clam.sh
        container: qc.ver_smelly-lilac-dolphin
timeout: 5400
